title: Jeanclyde Cruz Portfolio
logo: /assets/img/jc-logo.png
description: 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
author: Jeanclyde Cruz

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
enable_player: true